### ISSUE TITLE
Ability to set target folder

### ISSUE THREAD

**Issue by DanielRiek** [olia-dev/kopano-webapp-fetchmail#1]
Thanks for the Plugin!

It would be great to be able to specify a target folder for the fetched mails.

**Comment by olia-dev** [comment]
fetchmail (not the plugin, the program) doesn't support such an action, and since the plugin only configures fetchmail that's not possible.

But you can create a simple filter rule in kopano:

- Go to Settings => Rules => New
![fetchmail_settings_rules](https://user-images.githubusercontent.com/26431009/28934170-3e258fee-7880-11e7-90a6-0516f748ed24.png)

- And input the correct settings
![fetchmail_settings_rules_new](https://user-images.githubusercontent.com/26431009/28934202-566af22e-7880-11e7-8e52-5cfec4ca77c4.png)
